name: Slack Notifications

on:
  pull_request:
    branches: [ master ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@master
      with:
        args: ''{\"channel\":\"C014RMKG6H2\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"You have a new request:\n*<${{ github.event.pull_request._links.html.href }}|View Pull Request>*\"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Type:*\nComputer (laptop)\"},{\"type\":\"mrkdwn\",\"text\":\"*When:*\nSubmitted Aut 10\"},{\"type\":\"mrkdwn\",\"text\":\"*Last Update:*\nMar 10, 2015 (3 years, 5 months)\"},{\"type\":\"mrkdwn\",\"text\":\"*Reason:*\nAll vowel keys aren't working.\"},{\"type\":\"mrkdwn\",\"text\":\"*Specs:*\n\\"Cheetah Pro 15\\" - Fast, really fast\\"\"}]}]}''
