name: Slack Notifications

on:
  pull_request:
    branches: [ master ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C014RMKG6H2\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:*\n${{ github.event.pull_request.user.login }}\n*State:*\n${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"plain_text\",\"text\":\"<${{ github.event.pull_request._links.html.href }}|View Pull Request>\",\"emoji\":true}}]}'
